"""Make duration_minutes nullable

Revision ID: bfdacbe8f207
Revises: 74afbdb7c740
Create Date: 2025-12-28 15:54:50.501067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfdacbe8f207'
down_revision: Union[str, Sequence[str], None] = '74afbdb7c740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_stats')
    op.add_column('exercises', sa.Column('ai_generated', sa.Boolean(), nullable=False))
    op.alter_column('workouts', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('exercises', 'ai_generated')
    op.create_table('weekly_stats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('week_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_volume', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_sets', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_reps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('weekly_stats_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('weekly_stats_pkey'))
    )
    # ### end Alembic commands ###
